"""
SU2 Adjoint Configuration Generator (Discrete Adjoint).

Generates SU2 .cfg files for discrete adjoint mode (SU2_CFD_ADJ).
  - Objective: drag coefficient (CD) or lift-drag ratio
  - Design variables: surface coordinates (for CST projection later)
  - Uses converged primal flow solution as starting point
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional


def generate_adjoint_config(
    mesh_filename: str,
    primal_config_filename: str,
    objective: str = "DRAG",
    n_iter: int = 500,
    cfl_adjoint: float = 1.0,
    output_dir: str = ".",
    restart_filename: Optional[str] = None,
) -> str:
    """
    Generate the full text of an SU2 discrete adjoint configuration file.

    Parameters
    ----------
    mesh_filename : str
        Path to mesh file (same as primal).
    primal_config_filename : str
        Path to the primal configuration file (for parameter reference).
    objective : str
        Objective function: "DRAG" (Cd), "LIFT" (Cl), or "EFFICIENCY" (Cl/Cd).
    n_iter : int
        Number of adjoint iterations.
    cfl_adjoint : float
        CFL number for adjoint solver.
    output_dir : str
        Directory for output files.
    restart_filename : str, optional
        Path to adjoint restart file (for continuing adjoint).

    Returns
    -------
    config_text : str
        Complete SU2 adjoint configuration file text.
    """
    # Objective function mapping
    objective_map = {
        "DRAG": "DRAG_COEFFICIENT",
        "LIFT": "LIFT_COEFFICIENT",
        "EFFICIENCY": "EFFICIENCY",
        "SURFACE_SENSITIVITY": "SURFACE_SENSITIVITY",
    }
    obj_value = objective_map.get(objective.upper(), "DRAG_COEFFICIENT")

    # Adjoint solver type (mirrors primal)
    solver = "INC_RANS" if "INC_" in open(primal_config_filename).read().split("\n")[0] else "RANS"

    lines = [
        f"% ------- SU2 Discrete Adjoint Configuration -------",
        f"% Generated by airfoil_discovery.aso.config_adjoint",
        f"% Objective: {objective}",
        f"",
        f"% ------------ Solver ------------",
        f"SOLVER= {solver}",
        f"MATH_PROBLEM= DISCRETE_ADJOINT",
        f"RESTART_SOL= {'YES' if restart_filename else 'NO'}",
        f"",
        f"% ------------ Objective Function ------------",
        f"OBJECTIVE_FUNCTION= {obj_value}",
        f"",
        f"% ------------ Design Variables (Surface) ------------",
        "DV_KIND= SURFACE",
        "DV_PARAM= ( AIRFOIL, 0.0, 100.0 )",
        "DV_MARKER= ( airfoil )",
        "",
        f"% ------------ Mesh (same as primal) ------------",
        f"MESH_FILENAME= {mesh_filename}",
        "MESH_FORMAT= SU2",
        "",
        f"% ------------ Boundary Conditions (same as primal) ------------",
        "MARKER_HEATFLUX= ( airfoil, 0.0 )",
        "MARKER_FAR= ( farfield )",
        "MARKER_MONITORING= ( airfoil )",
        "MARKER_PLOTTING= ( airfoil )",
        "MARKER_EULER= ( symmetry )",
        "",
        f"% ------------ Adjoint Numerical Method ------------",
        "CONV_NUM_METHOD_FLOW= FDS",
        "CONV_NUM_METHOD_TURB= ROE_TURB",
        "NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES",
        "NUM_METHOD_GRAD_RECON= LEAST_SQUARES",
        "",
        f"% ------------ MUSCL for Adjoint ------------",
        "MUSCL_FLOW= YES",
        "MUSCL_TURB= YES",
        "SLOPE_LIMITER_FLOW= VENKATAKRISHNAN_WANG",
        "SLOPE_LIMITER_TURB= VENKATAKRISHNAN_WANG",
        "",
        f"% ------------ Time Integration ------------",
        "TIME_DISCRE_FLOW= EULER_IMPLICIT",
        "TIME_DISCRE_TURB= EULER_IMPLICIT",
        f"CFL_NUMBER_ADJFLOW= {cfl_adjoint}",
        f"CFL_NUMBER_ADJTURB= {cfl_adjoint}",
        "CFL_ADAPT= NO",
        "",
        f"% ------------ Iterations ------------",
        f"ITER= {n_iter}",
        "",
        f"% ------------ Linear Solver ------------",
        "LINEAR_SOLVER= FGMRES",
        "LINEAR_SOLVER_PREC= ILU",
        "LINEAR_SOLVER_ERROR= 1e-10",
        "LINEAR_SOLVER_ITER= 20",
        "",
        f"% ------------ Adjoint-Specific ------------",
        "ADJ_MACH_NUMBER= 0.1",
        "ADJ_AOA= 0.0",
        "ADJ_SIDESLIP_ANGLE= 0.0",
        "ADJ_REYNOLDS_NUMBER= 1e5",
        "ADJ_FREESTREAM_TEMPERATURE= 288.15",
        "ADJ_FREESTREAM_PRESSURE= 101325.0",
        "",
        f"% ------------ Output ------------",
        "TABULAR_FORMAT= CSV",
        "CONV_FILENAME= history_adj",
        "RESTART_FILENAME= restart_adj",
        "VOLUME_FILENAME= adjoint",
        "SURFACE_FILENAME= surface_adjoint",
        f"OUTPUT_FILES= (RESTART, SURFACE_CSV)",
        f"OUTPUT_WRT_FREQ= 100",
        f"SCREEN_OUTPUT= (INNER_ITER, RMS_RES)",
        f"HISTORY_OUTPUT= (INNER_ITER, RMS_RES)",
        f"CONV_STARTITER= 10",
        f"OUTPUT_DIR= {output_dir}",
    ]

    if restart_filename:
        lines.append(f"SOLUTION_FILENAME= {restart_filename}")

    return "\n".join(lines)


def write_adjoint_config(
    output_path: Path,
    mesh_filename: str,
    primal_config_filename: str,
    objective: str = "DRAG",
    n_iter: int = 500,
    cfl_adjoint: float = 1.0,
    restart_filename: Optional[str] = None,
) -> Path:
    """
    Generate and write the SU2 discrete adjoint configuration file.

    Returns
    -------
    Path
        The path to the written config file.
    """
    text = generate_adjoint_config(
        mesh_filename=mesh_filename,
        primal_config_filename=primal_config_filename,
        objective=objective,
        n_iter=n_iter,
        cfl_adjoint=cfl_adjoint,
        restart_filename=restart_filename,
    )
    output_path.write_text(text, encoding="utf-8")
    return output_path