"""
SU2 Primal Configuration Generator (RANS + Transition).

Generates SU2 .cfg files for:
  - 2D compressible/incompressible RANS
  - k-ω SST turbulence model
  - Langtry-Menter γ-Re_θ transition model (LM2009)
  - Roe upwind flux with MUSCL reconstruction and Venkatakrishnan limiter
  - Second-order spatial accuracy
  - CFL ramping for robust convergence at low Re
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional


def generate_primal_config(
    mesh_filename: str,
    aoa_deg: float = 4.0,
    reynolds: float = 1e5,
    mach: float = 0.1,
    ref_length: float = 1.0,
    ref_area: float = 1.0,
    n_iter: int = 3000,
    cfl_initial: float = 1.0,
    cfl_final: float = 5.0,
    transition_model: bool = True,
    turbulence_intensity: float = 0.001,
    turb_viscosity_ratio: float = 5.0,
    output_dir: str = ".",
    restart_filename: Optional[str] = None,
) -> str:
    """
    Generate the full text of an SU2 primal configuration file.

    Parameters
    ----------
    mesh_filename : str
        Path to mesh file (relative to working directory).
    aoa_deg : float
        Angle of attack in degrees.
    reynolds : float
        Chord Reynolds number.
    mach : float
        Freestream Mach number (use <= 0.3 for incompressible).
    ref_length, ref_area : float
        Reference length (chord) and area.
    n_iter : int
        Number of iterations.
    cfl_initial, cfl_final : float
        CFL number ramp range.
    transition_model : bool
        If True, activate γ-Re_θ transition model (LM).
    turbulence_intensity : float
        Freestream turbulence intensity (fraction, e.g. 0.001 = 0.1%).
    turb_viscosity_ratio : float
        Freestream turbulent viscosity ratio (μ_t/μ).
    output_dir : str
        Directory for output files.
    restart_filename : str, optional
        Path to restart solution file (if restarting).

    Returns
    -------
    config_text : str
        Complete SU2 configuration file text.
    """
    # Solver type: Incompressible RANS for low Mach, compressible otherwise
    if mach < 0.3:
        solver = "INC_RANS"
        density_model = "CONSTANT"
        velocity_init = "1.0"
    else:
        solver = "RANS"
        density_model = "IDEAL_GAS"
        velocity_init = "1.0"

    # Turbulence model
    turb_model = "SST"

    # Transition model
    trans_model = "LM" if transition_model else "NONE"

    lines = [
        f"% ------- SU2 Primal Configuration -------",
        f"% Generated by airfoil_discovery.aso.config_primal",
        f"% Reynolds = {reynolds:.1e}, Mach = {mach}, AoA = {aoa_deg} deg",
        f"",
        f"% ------------ Solver ------------",
        f"SOLVER= {solver}",
        f"MATH_PROBLEM= DIRECT",
        f"RESTART_SOL= {'YES' if restart_filename else 'NO'}",
        f"",
        f"% ------------ Turbulence Model ------------",
        f"KIND_TURB_MODEL= {turb_model}",
        f"KIND_TRANS_MODEL= {trans_model}",
        f"",
        f"% ------------ Compressibility ------------",
        f"INC_DENSITY_MODEL= {density_model}",
        f"VISCOSITY_MODEL= CONSTANT_VISCOSITY",
        f"MU_CONSTANT= 1.78e-5",
        f"INC_VELOCITY_INIT= ( {velocity_init}, 0.0, 0.0 )",
        f"",
        f"% ------------ Freestream ------------",
        f"MACH_NUMBER= {mach}",
        f"AOA= {aoa_deg}",
        f"SIDESLIP_ANGLE= 0.0",
        f"REYNOLDS_NUMBER= {reynolds:.1f}",
        f"REYNOLDS_LENGTH= {ref_length}",
        f"FREESTREAM_TEMPERATURE= 288.15",
        f"FREESTREAM_PRESSURE= 101325.0",
        f"REF_ORIGIN_MOMENT_X= 0.25",
        f"REF_ORIGIN_MOMENT_Y= 0.00",
        f"REF_ORIGIN_MOMENT_Z= 0.00",
        f"REF_LENGTH= {ref_length}",
        f"REF_AREA= {ref_area}",
        f"",
        f"% ------------ Transition Model Parameters ------------",
    ]

    if transition_model:
        lines.extend([
            f"FREESTREAM_TURBULENCEINTENSITY= {turbulence_intensity}",
            f"FREESTREAM_TURB2LAMVISCRATIO= {turb_viscosity_ratio}",
            "",
        ])
    else:
        lines.extend([
            "FREESTREAM_TURBULENCEINTENSITY= 0.05",
            "FREESTREAM_TURB2LAMVISCRATIO= 100.0",
            "",
        ])

    lines.extend([
        f"% ------------ Mesh ------------",
        f"MESH_FILENAME= {mesh_filename}",
        f"MESH_FORMAT= SU2",
        f"",
        f"% ------------ Boundary Conditions ------------",
        "MARKER_HEATFLUX= ( airfoil, 0.0 )",
        "MARKER_FAR= ( farfield )",
        "MARKER_MONITORING= ( airfoil )",
        "MARKER_PLOTTING= ( airfoil )",
        "MARKER_EULER= ( symmetry )",
        "",
        f"% ------------ Numerical Method ------------",
        "CONV_NUM_METHOD_FLOW= FDS",         # Roe upwind
        # "CONV_NUM_METHOD_TURB= ROE_TURB",  # Removed: not supported in this SU2 version
        "NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES",
        "NUM_METHOD_GRAD_RECON= LEAST_SQUARES",
        "",
        f"% ------------ MUSCL & Limiter ------------",
        "MUSCL_FLOW= YES",
        "MUSCL_TURB= YES",
        "SLOPE_LIMITER_FLOW= VENKATAKRISHNAN_WANG",
        "SLOPE_LIMITER_TURB= VENKATAKRISHNAN_WANG",
        "VENKAT_LIMITER_COEFF= 0.05",  # Fixed: corrected parameter name for SU2 compatibility
        "",
        f"% ------------ Time Integration ------------",
        f"TIME_DISCRE_FLOW= EULER_IMPLICIT",
        f"TIME_DISCRE_TURB= EULER_IMPLICIT",
        f"CFL_NUMBER= {cfl_initial}",
        f"CFL_ADAPT= YES",
        f"CFL_ADAPT_PARAM= ( 0.5, 1.5, {cfl_initial}, {cfl_final} )",  # Fixed: correct CFL adapt format
        f"",
        f"% ------------ Iterations ------------",
        f"ITER= {n_iter}",
        # "INNER_ITER= 0",  # Removed: not needed for steady-state RANS
        "",
        f"% ------------ Linear Solver ------------",
        "LINEAR_SOLVER= FGMRES",
        "LINEAR_SOLVER_PREC= ILU",
        "LINEAR_SOLVER_ERROR= 1e-6",
        "LINEAR_SOLVER_ITER= 10",
        "",
        f"% ------------ Output ------------",
        "TABULAR_FORMAT= CSV",
        "CONV_FILENAME= history",
        "RESTART_FILENAME= restart_flow",
        "VOLUME_FILENAME= flow",
        "SURFACE_FILENAME= surface_flow",
        f"OUTPUT_FILES= (RESTART, PARAVIEW, SURFACE_CSV)",
        f"OUTPUT_WRT_FREQ= 100",
        f"SCREEN_OUTPUT= (INNER_ITER, RMS_RES, AERO_COEFF)",
        f"HISTORY_OUTPUT= (INNER_ITER, RMS_RES, AERO_COEFF)",
        f"CONV_STARTITER= 10",
        f"CONV_CAUCHY_ELEMS= 100",
        f"CONV_CAUCHY_EPS= 1e-6",
        # Removed OUTPUT_DIR: not supported in this SU2 version
    ])

    if restart_filename:
        lines.append(f"SOLUTION_FILENAME= {restart_filename}")

    return "\n".join(lines)


def write_primal_config(
    output_path: Path,
    mesh_filename: str,
    aoa_deg: float = 4.0,
    reynolds: float = 1e5,
    mach: float = 0.1,
    n_iter: int = 3000,
    cfl_initial: float = 1.0,
    cfl_final: float = 5.0,
    transition_model: bool = True,
    turbulence_intensity: float = 0.001,
    turb_viscosity_ratio: float = 5.0,
    restart_filename: Optional[str] = None,
) -> Path:
    """
    Generate and write the SU2 primal configuration file.

    Returns
    -------
    Path
        The path to the written config file.
    """
    text = generate_primal_config(
        mesh_filename=mesh_filename,
        aoa_deg=aoa_deg,
        reynolds=reynolds,
        mach=mach,
        n_iter=n_iter,
        cfl_initial=cfl_initial,
        cfl_final=cfl_final,
        transition_model=transition_model,
        turbulence_intensity=turbulence_intensity,
        turb_viscosity_ratio=turb_viscosity_ratio,
        restart_filename=restart_filename,
    )
    output_path.write_text(text, encoding="utf-8")
    return output_path