"""
SU2 Primal Configuration Generator (RANS + Transition).

Generates SU2 .cfg files for:
  - 2D compressible/incompressible RANS
  - k-ω SST turbulence model
  - Langtry-Menter γ-Re_θ transition model (LM2009)
  - Roe upwind flux with MUSCL reconstruction and Venkatakrishnan limiter
  - Second-order spatial accuracy
  - CFL ramping for robust convergence at low Re
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Optional

from airfoil_discovery.cfd.physics import (
    RHO_AIR,
    dynamic_viscosity_for_unit_velocity,
)


def generate_primal_config(
    mesh_filename: str,
    aoa_deg: float = 4.0,
    reynolds: float = 1e5,
    mach: float = 0.1,
    ref_length: float = 1.0,
    ref_area: float = 1.0,
    n_iter: int = 500,
    cfl_initial: float = 1.5,
    cfl_final: float = 50.0,
    cfl_adapt: bool = True,
    muscl: bool = False,
    slope_limiter_flow: str = "NONE",
    slope_limiter_turb: str = "NONE",
    transition_model: bool = True,
    turbulence_intensity: float = 0.001,
    turb_viscosity_ratio: float = 5.0,
    use_cold_start: bool = True,
    output_dir: str = ".",
    restart_filename: Optional[str] = None,
) -> str:
    """
    Generate the full text of an SU2 primal configuration file.
    """
    # Force compressible RANS for transition modeling support
    # Transition model (LM) requires compressible RANS solver
    solver = "RANS"
    density_model = "IDEAL_GAS"
    conv_field = "RMS_DENSITY"
    conv_scheme = "ROE"
    use_inc_density = False

    # Use the working viscosity from prod_run_output
    mu = 1.225e-05
    # Use AoA-based velocity initialization as in prod_run_output
    aoa_rad = math.radians(aoa_deg)
    vx = math.cos(aoa_rad)
    vy = math.sin(aoa_rad)
    turb_model = "SST"
    trans_model = "LM" if transition_model else "NONE"
    cfl_number = cfl_initial
    use_cfl_adapt = cfl_adapt
    cfl_adapt_str = "YES" if use_cfl_adapt else "NO"
    
    # Transition model requires specific numerical schemes
    if transition_model:
        # Use ROE with MUSCL for transition modeling
        conv_scheme = "ROE"
        muscl = True
        slope_limiter_flow = "VENKATAKRISHNAN_WANG"
        venkat_coeff = 0.03  # Lower coefficient for transition stability
        conv_scheme_turb = "SCALAR_UPWIND"
        muscl_turb = False
        n_iter = 1500  # More iterations for transition convergence
    else:
        # Conservative settings for SST-only
        conv_scheme = "ROE"
        muscl = muscl
        slope_limiter_flow = slope_limiter_flow if muscl else "NONE"
        venkat_coeff = 0.05
        conv_scheme_turb = "SCALAR_UPWIND"
        muscl_turb = muscl
        n_iter = n_iter

    lines = [
        f"% ------- SU2 Primal Configuration -------",
        f"% Generated by airfoil_discovery.aso.config_primal",
        f"% Reynolds = {reynolds:.1e}, Mach = {mach}, AoA = {aoa_deg} deg",
        f"",
        f"% ------------ Solver ------------",
        f"SOLVER= {solver}",
        f"MATH_PROBLEM= DIRECT",
        f"RESTART_SOL= {'YES' if restart_filename else 'NO'}",
        f"",
        f"% ------------ Turbulence Model ------------",
        f"KIND_TURB_MODEL= {turb_model}",
        f"KIND_TRANS_MODEL= {trans_model}",
        f"",
        f"% ------------ Compressibility ------------",
    ]
    
    if use_inc_density:
        lines.extend([
            f"INC_DENSITY_MODEL= {density_model}",
            f"INC_DENSITY_INIT= {RHO_AIR}",
            f"VISCOSITY_MODEL= CONSTANT_VISCOSITY",
            f"MU_CONSTANT= {mu:.8e}",
            f"INC_VELOCITY_INIT= ( {vx:.8f}, {vy:.8f}, 0.0 )",
        ])
    else:
        lines.extend([
            f"VISCOSITY_MODEL= CONSTANT_VISCOSITY",
            f"MU_CONSTANT= {mu:.8e}",
        ])
    
    lines.extend([
        "",
        f"% ------------ Freestream ------------",
        f"MACH_NUMBER= {mach}",
        f"AOA= {aoa_deg}",
        f"SIDESLIP_ANGLE= 0.0",
        f"REYNOLDS_NUMBER= {reynolds:.1f}",
        f"REYNOLDS_LENGTH= {ref_length}",
        f"FREESTREAM_VELOCITY= ( {vx:.8f}, {vy:.8f}, 0.0 )",
        f"FREESTREAM_DENSITY= {RHO_AIR}",
        f"FREESTREAM_PRESSURE= 101325.0",
        f"FREESTREAM_TEMPERATURE= 288.15",
        f"REF_ORIGIN_MOMENT_X= 0.25",
        f"REF_ORIGIN_MOMENT_Y= 0.00",
        f"REF_ORIGIN_MOMENT_Z= 0.00",
        f"REF_LENGTH= {ref_length}",
        f"REF_AREA= {ref_area}",
        f"",
        f"% ------------ Transition Model Parameters ------------",
    ])

    if transition_model:
        lines.extend([
            f"FREESTREAM_TURBULENCEINTENSITY= {turbulence_intensity}",
            f"FREESTREAM_TURB2LAMVISCRATIO= {turb_viscosity_ratio}",
            "",
        ])
    else:
        lines.extend([
            "FREESTREAM_TURBULENCEINTENSITY= 0.05",
            "FREESTREAM_TURB2LAMVISCRATIO= 100.0",
            "",
        ])

    lines.extend([
        f"% ------------ Mesh ------------",
        f"MESH_FILENAME= {mesh_filename}",
        f"MESH_FORMAT= SU2",
        f"",
        f"% ------------ Boundary Conditions ------------",
        "MARKER_HEATFLUX= ( airfoil, 0.0 )",
        "MARKER_FAR= ( farfield )",
        "MARKER_MONITORING= ( airfoil )",
        "MARKER_PLOTTING= ( airfoil )",
        "",
        f"% ------------ Numerical Method ------------",
        f"CONV_NUM_METHOD_FLOW= {conv_scheme}",
        f"CONV_NUM_METHOD_TURB= {conv_scheme_turb}",
        "NUM_METHOD_GRAD= GREEN_GAUSS",
        "NUM_METHOD_GRAD_RECON= LEAST_SQUARES",
        "",
        f"% ------------ MUSCL & Limiter ------------",
        f"MUSCL_FLOW= {'YES' if muscl else 'NO'}",
        f"MUSCL_TURB= {'YES' if muscl_turb else 'NO'}",
        f"SLOPE_LIMITER_FLOW= {slope_limiter_flow if muscl else 'NONE'}",
        f"SLOPE_LIMITER_TURB= {slope_limiter_turb if muscl_turb else 'NONE'}",
        f"VENKAT_LIMITER_COEFF= {venkat_coeff}",
        "",
        f"% ------------ Time Integration ------------",
        f"TIME_DISCRE_FLOW= EULER_IMPLICIT",
        f"TIME_DISCRE_TURB= EULER_IMPLICIT",
        f"CFL_NUMBER= {cfl_number}",
        f"CFL_ADAPT= {cfl_adapt_str}",
    ])
    if use_cfl_adapt:
        lines.append(f"CFL_ADAPT_PARAM= ( 0.5, 1.2, 1.0, 30.0 )")
        lines.append("CFL_REDUCTION_TURB= 0.95")
    lines.extend([
        f"",
        f"% ------------ Iterations ------------",
        f"ITER= {n_iter}",
        "",
        f"% ------------ Linear Solver ------------",
        "LINEAR_SOLVER= FGMRES",
        "LINEAR_SOLVER_PREC= ILU",
        "LINEAR_SOLVER_ERROR= 1E-6",
        "LINEAR_SOLVER_ITER= 10",
        "",
        f"% ------------ Convergence Criteria ------------",
        f"CONV_FIELD= {conv_field}",
        "CONV_STARTITER= 10",
        "CONV_CAUCHY_ELEMS= 50",
        "CONV_CAUCHY_EPS= 1e-6",
        "",
        f"% ------------ Output ------------",
        "TABULAR_FORMAT= CSV",
        "CONV_FILENAME= history",
        "RESTART_FILENAME= restart_flow",
        "VOLUME_FILENAME= flow",
        "SURFACE_FILENAME= surface_flow",
        f"OUTPUT_FILES= (RESTART, SURFACE_CSV)",
        f"OUTPUT_WRT_FREQ= 50",
        f"SCREEN_OUTPUT= (INNER_ITER, RMS_RES, AERO_COEFF)",
        f"HISTORY_OUTPUT= (INNER_ITER, RMS_RES, AERO_COEFF)",
    ])

    if restart_filename:
        lines.append(f"SOLUTION_FILENAME= {restart_filename}")

    return "\n".join(lines)


def write_primal_config(
    output_path: Path,
    mesh_filename: str,
    aoa_deg: float = 4.0,
    reynolds: float = 1e5,
    mach: float = 0.1,
    n_iter: int = 500,
    cfl_initial: float = 1.5,
    cfl_final: float = 50.0,
    cfl_adapt: bool = True,
    muscl: bool = True,
    slope_limiter_flow: str = "VENKATAKRISHNAN_WANG",
    slope_limiter_turb: str = "VENKATAKRISHNAN",
    transition_model: bool = True,
    turbulence_intensity: float = 0.001,
    turb_viscosity_ratio: float = 5.0,
    restart_filename: Optional[str] = None,
    use_cfl_adapt: bool = True,
) -> Path:
    text = generate_primal_config(
        mesh_filename=mesh_filename,
        aoa_deg=aoa_deg,
        reynolds=reynolds,
        mach=mach,
        n_iter=n_iter,
        cfl_initial=cfl_initial,
        cfl_final=cfl_final,
        cfl_adapt=use_cfl_adapt,
        muscl=muscl,
        slope_limiter_flow=slope_limiter_flow,
        slope_limiter_turb=slope_limiter_turb,
        transition_model=transition_model,
        turbulence_intensity=turbulence_intensity,
        turb_viscosity_ratio=turb_viscosity_ratio,
        restart_filename=restart_filename,
    )
    output_path.write_text(text, encoding="utf-8")
    return output_path
