"""
Mesh Deformation via SU2_DEF.

Wraps SU2's built-in grid deformation tool (SU2_DEF) to smoothly warp
the computational mesh around updated CST airfoil coordinates.

The deformation uses the linear elasticity analogy (FEA) built into SU2,
which preserves mesh quality (orthogonality, y+ distribution) for
moderate shape changes typical in gradient-based optimization.
"""

from __future__ import annotations

import subprocess
import logging
import os
from pathlib import Path
from typing import Optional

import numpy as np

from .cst import compute_airfoil_coordinates, N_DESIGN_VARS

logger = logging.getLogger(__name__)


def generate_su2_def_config(
    mesh_input: str,
    mesh_output: str,
    marker: str = "airfoil",
    n_iter: int = 500,
    young_modulus: float = 1e6,
    poisson_ratio: float = 0.3,
) -> str:
    """
    Generate an SU2_DEF configuration file for mesh deformation.

    SU2_DEF uses a linear elasticity (FEA) analogy to propagate
    boundary displacements into the volume mesh.

    Parameters
    ----------
    mesh_input : str
        Path to input mesh file (SU2 format).
    mesh_output : str
        Path to output deformed mesh file.
    marker : str
        Boundary marker to apply displacement to.
    n_iter : int
        Number of FEA iterations for deformation.
    young_modulus, poisson_ratio : float
        Material properties for elasticity analogy.

    Returns
    -------
    config_text : str
    """
    lines = [
        f"% ------- SU2_DEF Mesh Deformation Config -------",
        f"% Generated by airfoil_discovery.aso.mesh_deform",
        f"",
        f"% ------------ Solver ------------",
        "SOLVER= ELASTICITY",  # SU2_DEF uses ELASTICITY solver for mesh deformation
        "MATH_PROBLEM= DIRECT",
        "",
        f"% ------------ Mesh ------------",
        f"MESH_FILENAME= {mesh_input}",
        f"MESH_OUT_FILENAME= {mesh_output}",
        "MESH_FORMAT= SU2",
        "",
        f"% ------------ Boundary Conditions ------------",
        f"MARKER_HEATFLUX= ( {marker}, 0.0 )",
        "MARKER_FAR= ( farfield )",
        "",
        f"% ------------ Deformation Parameters ------------",
        f"DEFORM_STIFFNESS_TYPE= INVERSE_VOLUME",
        f"DEFORM_LINEAR_SOLVER= FGMRES",
        f"DEFORM_LINEAR_SOLVER_PREC= ILU",
        f"DEFORM_LINEAR_SOLVER_ITER= 100",
        f"DEFORM_LINEAR_SOLVER_ERROR= 1e-10",
        f"DEFORM_NONLINEAR_ITER= {n_iter}",
        f"DEFORM_CONSOLE_OUTPUT= YES",
        "",
        f"% ------------ Elasticity Parameters ------------",
        f"DEFORM_ELASTICITY_MODULUS= {young_modulus}",
        f"DEFORM_POISSONS_RATIO= {poisson_ratio}",
        "",
        f"% ------------ Output ------------",
        "TABULAR_FORMAT= CSV",
        "CONV_FILENAME= history_def",
        "OUTPUT_FILES= (RESTART)",
        "OUTPUT_WRT_FREQ= 100",
    ]
    return "\n".join(lines)


def write_airfoil_dat(
    dv: np.ndarray,
    output_path: Path,
    n_pts: int = 200,
    te_thickness: float = 0.003,
) -> None:
    """
    Write airfoil coordinates to a .dat file for SU2_DEF boundary displacement.

    The .dat file format is:
      airfoil_name
      x1  y1
      x2  y2
      ...

    Parameters
    ----------
    dv : np.ndarray, shape (12,)
        CST design variables.
    output_path : Path
        Path to write the .dat file.
    n_pts : int
        Number of points per surface.
    te_thickness : float
        Trailing edge thickness.
    """
    coords = compute_airfoil_coordinates(dv, n_pts_per_surface=n_pts, te_thickness=te_thickness)
    lines = ["airfoil"]
    for x, y in coords:
        lines.append(f"  {x:.10f}  {y:.10f}")
    output_path.write_text("\n".join(lines), encoding="utf-8")


def run_su2_def(
    su2_def_bin: str,
    config_path: Path,
    work_dir: Path,
    timeout: float = 300.0,
) -> bool:
    """
    Run SU2_DEF for mesh deformation.

    Parameters
    ----------
    su2_def_bin : str
        Path to SU2_DEF executable.
    config_path : Path
        Path to SU2_DEF configuration file.
    work_dir : Path
        Working directory (where mesh files are).
    timeout : float
        Timeout in seconds.

    Returns
    -------
    success : bool
    """
    cmd = [su2_def_bin, config_path.name]
    creation_flags = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0

    logger.info(f"Running SU2_DEF: {' '.join(cmd)} in {work_dir}")

    try:
        result = subprocess.run(
            cmd,
            cwd=work_dir,
            capture_output=True,
            text=True,
            timeout=timeout,
            creationflags=creation_flags,
        )
    except subprocess.TimeoutExpired:
        logger.error(f"SU2_DEF timed out after {timeout}s")
        return False
    except FileNotFoundError:
        logger.error(f"SU2_DEF not found: {su2_def_bin}")
        return False
    except Exception as e:
        logger.error(f"SU2_DEF execution error: {e}")
        return False

    # Log output
    (work_dir / "su2_def_stdout.log").write_text(result.stdout, encoding="utf-8", errors="ignore")
    (work_dir / "su2_def_stderr.log").write_text(result.stderr, encoding="utf-8", errors="ignore")

    if result.returncode != 0:
        logger.error(
            f"SU2_DEF failed (rc={result.returncode}): "
            f"{result.stderr[:500] if result.stderr else '(no stderr)'}"
        )
        return False

    logger.info(f"SU2_DEF completed successfully (rc={result.returncode})")
    return True


def deform_mesh(
    su2_def_bin: str,
    original_mesh_path: Path,
    dv_old: np.ndarray,
    dv_new: np.ndarray,
    work_dir: Path,
    marker: str = "airfoil",
    n_pts: int = 200,
    te_thickness: float = 0.003,
    n_iter_def: int = 500,
) -> Optional[Path]:
    """
    Deform the mesh from the old airfoil shape to the new one.

    The process:
    1. Write old and new airfoil .dat files.
    2. Generate SU2_DEF config.
    3. Run SU2_DEF to deform the mesh.
    4. Return path to deformed mesh.

    Parameters
    ----------
    su2_def_bin : str
        Path to SU2_DEF executable.
    original_mesh_path : Path
        Path to the original (undeformed) mesh file.
    dv_old : np.ndarray, shape (12,)
        CST design variables of the old (baseline) airfoil.
    dv_new : np.ndarray, shape (12,)
        CST design variables of the new (target) airfoil.
    work_dir : Path
        Working directory for intermediate files.
    marker : str
        Boundary marker for displacement.
    n_pts : int
        Number of points for airfoil .dat files.
    te_thickness : float
        Trailing edge thickness.
    n_iter_def : int
        Number of SU2_DEF iterations.

    Returns
    -------
    deformed_mesh_path : Path or None
        Path to the deformed mesh if successful, None otherwise.
    """
    if dv_old.shape != dv_new.shape or dv_old.shape[0] != 12:
        logger.error(f"Invalid design vector shapes: old={dv_old.shape}, new={dv_new.shape}")
        return None
    if np.any(np.isnan(dv_old)) or np.any(np.isnan(dv_new)):
        logger.error("Design vectors contain NaN values")
        return None

    if not original_mesh_path.exists():
        logger.error(f"Original mesh not found: {original_mesh_path}")
        return None

    work_dir.mkdir(parents=True, exist_ok=True)

    # Write old and new airfoil coordinates
    old_dat = work_dir / "airfoil_old.dat"
    new_dat = work_dir / "airfoil_new.dat"
    write_airfoil_dat(dv_old, old_dat, n_pts=n_pts, te_thickness=te_thickness)
    write_airfoil_dat(dv_new, new_dat, n_pts=n_pts, te_thickness=te_thickness)

    # Copy original mesh to working directory
    mesh_input = work_dir / "mesh_original.su2"
    if original_mesh_path != mesh_input:
        import shutil
        shutil.copy2(original_mesh_path, mesh_input)

    # Output mesh path
    mesh_output = work_dir / "mesh_deformed.su2"

    # Generate SU2_DEF config
    def_config = work_dir / "config_deform.cfg"
    config_text = generate_su2_def_config(
        mesh_input=mesh_input.name,
        mesh_output=mesh_output.name,
        marker=marker,
        n_iter=n_iter_def,
    )
    def_config.write_text(config_text, encoding="utf-8")

    # Run SU2_DEF
    success = run_su2_def(su2_def_bin, def_config, work_dir)

    # Check if output file exists
    if success:
        if mesh_output.exists():
            logger.info(f"Mesh deformed successfully: {mesh_output}")
            return mesh_output
        else:
            # Check for alternative output names that SU2_DEF might use
            possible_outputs = [
                mesh_output,
                work_dir / f"{mesh_input.stem}_deformed.su2",
                work_dir / f"{mesh_input.stem}_def.su2",
                work_dir / "mesh_out.su2"
            ]
            for alt_output in possible_outputs:
                if alt_output.exists():
                    logger.info(f"Mesh deformed successfully (found as {alt_output.name}): {alt_output}")
                    return alt_output
            
            # List files to help debug
            files_in_dir = list(work_dir.glob("*.su2"))
            logger.error(f"SU2_DEF succeeded but no output mesh found. Files in {work_dir}: {[f.name for f in files_in_dir]}")
            logger.error("Mesh deformation failed")
            return None
    else:
        logger.error("Mesh deformation failed")
        return None


def compute_mesh_displacement(
    dv_old: np.ndarray,
    dv_new: np.ndarray,
    n_pts: int = 200,
    te_thickness: float = 0.003,
) -> np.ndarray:
    """
    Compute the maximum surface displacement between two airfoil shapes.

    Useful for checking if the shape change is small enough for
    linear elasticity deformation to be valid.

    Parameters
    ----------
    dv_old, dv_new : np.ndarray, shape (12,)
    n_pts : int
    te_thickness : float

    Returns
    -------
    max_displacement : float
        Maximum Euclidean distance between corresponding surface points.
    """
    coords_old = compute_airfoil_coordinates(dv_old, n_pts_per_surface=n_pts, te_thickness=te_thickness)
    coords_new = compute_airfoil_coordinates(dv_new, n_pts_per_surface=n_pts, te_thickness=te_thickness)

    displacements = np.sqrt(np.sum((coords_new - coords_old) ** 2, axis=1))
    return float(np.max(displacements))